api = "0.7"

[buildpack]
id = "openfunction.go.of-functions-framework"
version = "0.5.0"
name = "Go - OpenFunction Functions Framework"

[[stacks]]
id = "google"

[[stacks]]
id = "openfunction.go115"

[[stacks]]
id = "openfunction.go116"